const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// Decode a base64url string (JWT uses base64url, not standard base64)
function decodeJwtPayload(token: string): Record<string, unknown> {
  const payload = token.split('.')[1]
  const padded = payload.replace(/-/g, '+').replace(/_/g, '/').padEnd(
    payload.length + (4 - payload.length % 4) % 4, '='
  )
  return JSON.parse(atob(padded))
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Missing auth token' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // The Supabase edge gateway already validates the JWT before our code runs.
    // We can safely decode the claims to get the user's email without a round-trip.
    const token = authHeader.replace('Bearer ', '')
    const claims = decodeJwtPayload(token)
    const email = claims.email as string | undefined

    if (!email) {
      return new Response(JSON.stringify({ error: 'No email in token' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const { pdfBase64, dogName, rangeLabel } = await req.json()
    const filename = `PupPulse-${dogName ?? 'Report'}-${new Date().toISOString().slice(0, 10)}.pdf`

    const emailRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${Deno.env.get('RESEND_API_KEY')}`,
      },
      body: JSON.stringify({
        from: 'PupPulse <onboarding@resend.dev>',
        to: [email],
        subject: `PupPulse Seizure Report — ${dogName ?? 'Your Dog'} (${rangeLabel})`,
        html: `
          <div style="font-family: sans-serif; max-width: 480px; margin: 0 auto;">
            <h2 style="color: #674CA7;">Your PupPulse Report is ready</h2>
            <p>Your seizure activity report for <strong>${rangeLabel}</strong> is attached.</p>
            <p style="color: #666;">
              You can forward this email directly to your veterinarian
              ahead of your next appointment.
            </p>
            <p style="color: #aaa; font-size: 12px; margin-top: 32px;">
              Generated by PupPulse
            </p>
          </div>
        `,
        attachments: [{
          filename,
          content: pdfBase64,
        }],
      }),
    })

    if (!emailRes.ok) {
      const body = await emailRes.text()
      return new Response(JSON.stringify({ error: body }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    return new Response(JSON.stringify({ success: true, sentTo: email }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
